// Backend Constants

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

export const USER_ROLES = {
  TEACHER: 'teacher',
  STUDENT: 'student',
};

export const EVALUATION_STATUS = {
  PENDING: 'pending',
  PROCESSING: 'processing',
  COMPLETED: 'completed',
  FAILED: 'failed',
};

export const ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  NO_TOKEN: 'NO_TOKEN',
  MISSING_FIELDS: 'MISSING_FIELDS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_ROLE: 'INVALID_ROLE',
  ROLE_MISMATCH: 'ROLE_MISMATCH',
};

export const ALLOWED_FILE_TYPES = ['pdf', 'png', 'jpg', 'jpeg', 'gif'];
export const MAX_FILE_SIZE = 50 * 1024 * 1024; // 50MB

export default {
  HTTP_STATUS,
  USER_ROLES,
  EVALUATION_STATUS,
  ERROR_CODES,
  ALLOWED_FILE_TYPES,
  MAX_FILE_SIZE,
};
